@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="mb-3 row">
                <label for="user" class="col-sm-2 col-form-label">As a</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="user" placeholder="<type of user>" maxlength="50">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="want" class="col-sm-2 col-form-label">I want</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="want" placeholder="<to perform an action>" maxlength="100">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="can" class="col-sm-2 col-form-label">so that I can</label>
                <div class="col-sm-10">
                    <textarea class="form-control" id="can" rows="6" placeholder="<achieve some goal/benefit/value>"></textarea>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="test" class="col-sm-2 col-form-label">When I test it, I can</label>
                <div class="col-sm-10">
                    <textarea class="form-control" id="test" rows="6" placeholder="<do something for get expected result>"></textarea>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="cant" class="col-sm-2 col-form-label">and I hope I can't</label>
                <div class="col-sm-10">
                    <textarea class="form-control" id="cant" rows="6" placeholder="<do something wrong>"></textarea>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card border-info mb-6">
                <div class="card-header">Autogenerated Task Description</div>
                <div class="card-body">
                    <div class="d-flex">
                        <div class="col-md-10">
                            <h5 class="card-title" id="task_name">How to write a project task description that everyone on the team can understand</h5>
                        </div>
                        <div class="col-md-1">
                            <button id="copy_title" type="button" class="btn btn-secondary btn-sm"
                                    style="padding: 11px 13px; height: fit-content;">
                                <i class="bi bi-files"></i>
                            </button>
                        </div>
                    </div>
                    <hr>
                    <div class="card-text">
                        <div class="d-flex">
                            <div class="col-md-10">
                                <div id="user_text">
                                    As a project manager, I want to write a task description that everyone on the team understands.
                                </div>
                            </div>
                            <div class="col-md-1">
                                <button id="copy_description" type="button" class="btn btn-secondary btn-sm"
                                        style="padding: 11px 13px; height: fit-content;">
                                    <i class="bi bi-files"></i>
                                </button>
                            </div>
                        </div>

                        <div id="can_text">
                            So that I can open the website Task Beautifier and create a task via A User Story Template, I can use it for all new tasks, and all team members, who read that, can understand all the information from tasks without questions.
                        </div>
                        <div id="test_text">
                            When I test it, I can open the website and insert details into a template, and the website shall generate the task's title and description.
                        </div>
                        <div id="cant_text">
                            I hope I can't insert into &lt;type of user&gt; input more than 50 symbols and &lt;to perform an action&gt; input more than 100 symbols; Also I hope other inputs are optional (NOT required) and have no length limit
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-5 d-grid gap-2">
                <button id="clear" class="btn btn-primary" type="button">Clear form</button>
            </div>
        </div>
    </div>
</div>
<script>
    function copyTextToClipboard(text) {
        let textArea = document.createElement("textarea");
        textArea.style.position = 'fixed';
        textArea.style.top = 0;
        textArea.style.left = 0;
        textArea.style.width = '2em';
        textArea.style.height = '2em';
        textArea.style.padding = 0;
        textArea.style.border = 'none';
        textArea.style.outline = 'none';
        textArea.style.boxShadow = 'none';
        textArea.style.background = 'transparent';
        textArea.value = text;
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        try {
            let successful = document.execCommand('copy');
        } catch (err) {
            console.log('Oops, unable to copy');
        }
        document.body.removeChild(textArea);
    }
    function capitalizeFirstLetter(str) {
        return str.charAt(0).toUpperCase() + str.slice(1);
    }
    function beautifier() {
        let want = document.getElementById('want').value ?? '';
        let user = document.getElementById('user').value ?? '';
        let can = document.getElementById('can').value ?? '';
        let test = document.getElementById('test').value ?? '';
        let cant = document.getElementById('cant').value ?? '';
        document.getElementById('task_name').innerHTML = want ? capitalizeFirstLetter(want) : 'Create task description better';
        document.getElementById('user_text').innerHTML = user ? 'As a ' + user + ', I want to ' + want : '';
        document.getElementById('can_text').innerHTML = can ? 'So that I can ' + can : '';
        document.getElementById('test_text').innerHTML = test ? 'When I test it, I can ' + test : '';
        document.getElementById('cant_text').innerHTML = cant ? 'I hope I can\'t ' + cant : '';
    }
    document.getElementById('user').addEventListener('input', beautifier);
    document.getElementById('want').addEventListener('input', beautifier);
    document.getElementById('can').addEventListener('input', beautifier);
    document.getElementById('test').addEventListener('input', beautifier);
    document.getElementById('cant').addEventListener('input', beautifier);
    document.getElementById('clear').addEventListener('click', function () {
        document.getElementById('user').value = '';
        document.getElementById('want').value = '';
        document.getElementById('can').value = '';
        document.getElementById('test').value = '';
        document.getElementById('cant').value = '';
        document.getElementById('task_name').innerHTML = 'Write a task description that everyone on the team understands.';
        document.getElementById('user_text').innerHTML = 'As a project manager, I want to write a task description that everyone on the team understands.';
        document.getElementById('can_text').innerHTML = 'So that I can open the website Task Beautifier and create a task via A User Story Template, I can use it for all new tasks, and all team members, who read that, can understand all the information from tasks without questions.';
        document.getElementById('test_text').innerHTML = 'When I test it, I can open the website and insert details into a template, and the website shall generate the task\'s title and description.';
        document.getElementById('cant_text').innerHTML = 'I hope I can\'t insert into &lt;type of user&gt; input more than 50 symbols and &lt;to perform an action&gt; input more than 100 symbols; Also I hope other inputs are optional (NOT required) and have no length limit';
    });
    document.getElementById('copy_title').addEventListener('click', function () {
        copyTextToClipboard(document.getElementById('task_name').textContent);
    });
    document.getElementById('copy_description').addEventListener('click', function () {
        copyTextToClipboard(
            document.getElementById('task_name').textContent + `
            ` + document.getElementById('user_text').textContent + `
            ` + document.getElementById('user_text').textContent + `
            ` + document.getElementById('can_text').textContent + `
            ` + document.getElementById('test_text').textContent + `
            ` + document.getElementById('cant_text').textContent
        );
    });
</script>
@endsection
